### ISSUE TITLE
Design a logo for the Extension

### ISSUE THREAD

**Issue by kailashchoudhary11** [kailashchoudhary11/LeetConnect#2]
Design a logo for the extension which should support various screens.

You need to design the logo in these 3 sizes
16x16,
48x48,
128x128,

Create a new directory in /extension-ui/src/assets named logos
Name the logo files as icon16, icon48 and icon128 and add them to logos directory
Make a PR to the main branch

**Comment by Namnika** [comment]
I want to contribute to this!

**Comment by kailashchoudhary11** [comment]
> I want to contribute to this!

Sure you can start  working on it!
