### ISSUE TITLE
Design the Landing page for extension

### ISSUE THREAD

**Issue by kailashchoudhary11** [kailashchoudhary11/LeetConnect#3]
Create a landing page for the browser extension

The page should contain following components

1.) The avatar and username of the user profile that is open in the active tab
2.) A button to follow the user
3.) A list of leetcode users to whom the extension user is following
4.) An unfollow button beside every leetcode user in the list

**Comment by AtriChatterjee1** [comment]
Hey ! Do you need the design to this page or the code to it? In case you have the design , I would like to work on it

**Comment by kailashchoudhary11** [comment]
> Hey ! Do you need the design to this page or the code to it? In case you have the design , I would like to work on it

I need the design for the page.

**Comment by AtriChatterjee1** [comment]
Cool ! Can you assign me

**Comment by kailashchoudhary11** [comment]
> Cool ! Can you assign me

Sure, you can start working on it.

**Comment by Albert-2** [comment]
hey @kailashchoudhary11
I would very much like to work on this issue
can you please assign me under codepeak'23 
Thank you.....
happy coding.....

**Comment by kailashchoudhary11** [comment]
Hi, @AtriChatterjee1 any updates?

**Comment by AtriChatterjee1** [comment]
Hi, I am mostly done with the design. I am currently travelling, will put a PR tomorrow or day after

**Comment by kailashchoudhary11** [comment]
> Hi, I am mostly done with the design. I am currently travelling, will put a PR tomorrow or day after

Okay Great!

**Comment by kailashchoudhary11** [comment]
@AtriChatterjee1 any updates?
